// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: mount.proto

package mount_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeaweedMount_Configure_FullMethodName              = "/messaging_pb.SeaweedMount/Configure"
	SeaweedMount_RefreshVolumeLocations_FullMethodName = "/messaging_pb.SeaweedMount/RefreshVolumeLocations"
	SeaweedMount_HotRestartStatus_FullMethodName       = "/messaging_pb.SeaweedMount/HotRestartStatus"
	SeaweedMount_PrepareHotRestart_FullMethodName      = "/messaging_pb.SeaweedMount/PrepareHotRestart"
	SeaweedMount_CancelHotRestart_FullMethodName       = "/messaging_pb.SeaweedMount/CancelHotRestart"
)

// SeaweedMountClient is the client API for SeaweedMount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeaweedMountClient interface {
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	RefreshVolumeLocations(ctx context.Context, in *RefreshVolumeLocationsRequest, opts ...grpc.CallOption) (*RefreshVolumeLocationsResponse, error)
	HotRestartStatus(ctx context.Context, in *HotRestartStatusRequest, opts ...grpc.CallOption) (*HotRestartStatusResponse, error)
	PrepareHotRestart(ctx context.Context, in *PrepareHotRestartRequest, opts ...grpc.CallOption) (*PrepareHotRestartResponse, error)
	CancelHotRestart(ctx context.Context, in *CancelHotRestartRequest, opts ...grpc.CallOption) (*CancelHotRestartResponse, error)
}

type seaweedMountClient struct {
	cc grpc.ClientConnInterface
}

func NewSeaweedMountClient(cc grpc.ClientConnInterface) SeaweedMountClient {
	return &seaweedMountClient{cc}
}

func (c *seaweedMountClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, SeaweedMount_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seaweedMountClient) RefreshVolumeLocations(ctx context.Context, in *RefreshVolumeLocationsRequest, opts ...grpc.CallOption) (*RefreshVolumeLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshVolumeLocationsResponse)
	err := c.cc.Invoke(ctx, SeaweedMount_RefreshVolumeLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seaweedMountClient) HotRestartStatus(ctx context.Context, in *HotRestartStatusRequest, opts ...grpc.CallOption) (*HotRestartStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HotRestartStatusResponse)
	err := c.cc.Invoke(ctx, SeaweedMount_HotRestartStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seaweedMountClient) PrepareHotRestart(ctx context.Context, in *PrepareHotRestartRequest, opts ...grpc.CallOption) (*PrepareHotRestartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareHotRestartResponse)
	err := c.cc.Invoke(ctx, SeaweedMount_PrepareHotRestart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seaweedMountClient) CancelHotRestart(ctx context.Context, in *CancelHotRestartRequest, opts ...grpc.CallOption) (*CancelHotRestartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelHotRestartResponse)
	err := c.cc.Invoke(ctx, SeaweedMount_CancelHotRestart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeaweedMountServer is the server API for SeaweedMount service.
// All implementations must embed UnimplementedSeaweedMountServer
// for forward compatibility.
type SeaweedMountServer interface {
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	RefreshVolumeLocations(context.Context, *RefreshVolumeLocationsRequest) (*RefreshVolumeLocationsResponse, error)
	HotRestartStatus(context.Context, *HotRestartStatusRequest) (*HotRestartStatusResponse, error)
	PrepareHotRestart(context.Context, *PrepareHotRestartRequest) (*PrepareHotRestartResponse, error)
	CancelHotRestart(context.Context, *CancelHotRestartRequest) (*CancelHotRestartResponse, error)
	mustEmbedUnimplementedSeaweedMountServer()
}

// UnimplementedSeaweedMountServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeaweedMountServer struct{}

func (UnimplementedSeaweedMountServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedSeaweedMountServer) RefreshVolumeLocations(context.Context, *RefreshVolumeLocationsRequest) (*RefreshVolumeLocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshVolumeLocations not implemented")
}
func (UnimplementedSeaweedMountServer) HotRestartStatus(context.Context, *HotRestartStatusRequest) (*HotRestartStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HotRestartStatus not implemented")
}
func (UnimplementedSeaweedMountServer) PrepareHotRestart(context.Context, *PrepareHotRestartRequest) (*PrepareHotRestartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareHotRestart not implemented")
}
func (UnimplementedSeaweedMountServer) CancelHotRestart(context.Context, *CancelHotRestartRequest) (*CancelHotRestartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelHotRestart not implemented")
}
func (UnimplementedSeaweedMountServer) mustEmbedUnimplementedSeaweedMountServer() {}
func (UnimplementedSeaweedMountServer) testEmbeddedByValue()                      {}

// UnsafeSeaweedMountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeaweedMountServer will
// result in compilation errors.
type UnsafeSeaweedMountServer interface {
	mustEmbedUnimplementedSeaweedMountServer()
}

func RegisterSeaweedMountServer(s grpc.ServiceRegistrar, srv SeaweedMountServer) {
	// If the following call panics, it indicates UnimplementedSeaweedMountServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeaweedMount_ServiceDesc, srv)
}

func _SeaweedMount_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeaweedMountServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeaweedMount_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeaweedMountServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeaweedMount_RefreshVolumeLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshVolumeLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeaweedMountServer).RefreshVolumeLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeaweedMount_RefreshVolumeLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeaweedMountServer).RefreshVolumeLocations(ctx, req.(*RefreshVolumeLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeaweedMount_HotRestartStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotRestartStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeaweedMountServer).HotRestartStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeaweedMount_HotRestartStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeaweedMountServer).HotRestartStatus(ctx, req.(*HotRestartStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeaweedMount_PrepareHotRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareHotRestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeaweedMountServer).PrepareHotRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeaweedMount_PrepareHotRestart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeaweedMountServer).PrepareHotRestart(ctx, req.(*PrepareHotRestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeaweedMount_CancelHotRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelHotRestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeaweedMountServer).CancelHotRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeaweedMount_CancelHotRestart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeaweedMountServer).CancelHotRestart(ctx, req.(*CancelHotRestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SeaweedMount_ServiceDesc is the grpc.ServiceDesc for SeaweedMount service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeaweedMount_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messaging_pb.SeaweedMount",
	HandlerType: (*SeaweedMountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configure",
			Handler:    _SeaweedMount_Configure_Handler,
		},
		{
			MethodName: "RefreshVolumeLocations",
			Handler:    _SeaweedMount_RefreshVolumeLocations_Handler,
		},
		{
			MethodName: "HotRestartStatus",
			Handler:    _SeaweedMount_HotRestartStatus_Handler,
		},
		{
			MethodName: "PrepareHotRestart",
			Handler:    _SeaweedMount_PrepareHotRestart_Handler,
		},
		{
			MethodName: "CancelHotRestart",
			Handler:    _SeaweedMount_CancelHotRestart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mount.proto",
}
