// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: mount.proto

package mount_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CollectionCapacity int64                  `protobuf:"varint,1,opt,name=collection_capacity,json=collectionCapacity,proto3" json:"collection_capacity,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_mount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_mount_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigureRequest) GetCollectionCapacity() int64 {
	if x != nil {
		return x.CollectionCapacity
	}
	return 0
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_mount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_mount_proto_rawDescGZIP(), []int{1}
}

type RefreshVolumeLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshVolumeLocationsRequest) Reset() {
	*x = RefreshVolumeLocationsRequest{}
	mi := &file_mount_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshVolumeLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshVolumeLocationsRequest) ProtoMessage() {}

func (x *RefreshVolumeLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mount_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshVolumeLocationsRequest.ProtoReflect.Descriptor instead.
func (*RefreshVolumeLocationsRequest) Descriptor() ([]byte, []int) {
	return file_mount_proto_rawDescGZIP(), []int{2}
}

type RefreshVolumeLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshVolumeLocationsResponse) Reset() {
	*x = RefreshVolumeLocationsResponse{}
	mi := &file_mount_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshVolumeLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshVolumeLocationsResponse) ProtoMessage() {}

func (x *RefreshVolumeLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mount_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshVolumeLocationsResponse.ProtoReflect.Descriptor instead.
func (*RefreshVolumeLocationsResponse) Descriptor() ([]byte, []int) {
	return file_mount_proto_rawDescGZIP(), []int{3}
}

type HotRestartStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotRestartStatusRequest) Reset() {
	*x = HotRestartStatusRequest{}
	mi := &file_mount_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotRestartStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotRestartStatusRequest) ProtoMessage() {}

func (x *HotRestartStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mount_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotRestartStatusRequest.ProtoReflect.Descriptor instead.
func (*HotRestartStatusRequest) Descriptor() ([]byte, []int) {
	return file_mount_proto_rawDescGZIP(), []int{4}
}

type HotRestartStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OpenFileHandles      uint64                 `protobuf:"varint,1,opt,name=open_file_handles,json=openFileHandles,proto3" json:"open_file_handles,omitempty"`
	OpenDirectoryHandles uint64                 `protobuf:"varint,2,opt,name=open_directory_handles,json=openDirectoryHandles,proto3" json:"open_directory_handles,omitempty"`
	PendingAsyncFlushes  uint64                 `protobuf:"varint,3,opt,name=pending_async_flushes,json=pendingAsyncFlushes,proto3" json:"pending_async_flushes,omitempty"`
	Quiescent            bool                   `protobuf:"varint,4,opt,name=quiescent,proto3" json:"quiescent,omitempty"`
	BlockingNewHandles   bool                   `protobuf:"varint,5,opt,name=blocking_new_handles,json=blockingNewHandles,proto3" json:"blocking_new_handles,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HotRestartStatusResponse) Reset() {
	*x = HotRestartStatusResponse{}
	mi := &file_mount_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotRestartStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotRestartStatusResponse) ProtoMessage() {}

func (x *HotRestartStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mount_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotRestartStatusResponse.ProtoReflect.Descriptor instead.
func (*HotRestartStatusResponse) Descriptor() ([]byte, []int) {
	return file_mount_proto_rawDescGZIP(), []int{5}
}

func (x *HotRestartStatusResponse) GetOpenFileHandles() uint64 {
	if x != nil {
		return x.OpenFileHandles
	}
	return 0
}

func (x *HotRestartStatusResponse) GetOpenDirectoryHandles() uint64 {
	if x != nil {
		return x.OpenDirectoryHandles
	}
	return 0
}

func (x *HotRestartStatusResponse) GetPendingAsyncFlushes() uint64 {
	if x != nil {
		return x.PendingAsyncFlushes
	}
	return 0
}

func (x *HotRestartStatusResponse) GetQuiescent() bool {
	if x != nil {
		return x.Quiescent
	}
	return false
}

func (x *HotRestartStatusResponse) GetBlockingNewHandles() bool {
	if x != nil {
		return x.BlockingNewHandles
	}
	return false
}

type PrepareHotRestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareHotRestartRequest) Reset() {
	*x = PrepareHotRestartRequest{}
	mi := &file_mount_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareHotRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareHotRestartRequest) ProtoMessage() {}

func (x *PrepareHotRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mount_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareHotRestartRequest.ProtoReflect.Descriptor instead.
func (*PrepareHotRestartRequest) Descriptor() ([]byte, []int) {
	return file_mount_proto_rawDescGZIP(), []int{6}
}

type PrepareHotRestartResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Accepted      bool                      `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Status        *HotRestartStatusResponse `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareHotRestartResponse) Reset() {
	*x = PrepareHotRestartResponse{}
	mi := &file_mount_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareHotRestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareHotRestartResponse) ProtoMessage() {}

func (x *PrepareHotRestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mount_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareHotRestartResponse.ProtoReflect.Descriptor instead.
func (*PrepareHotRestartResponse) Descriptor() ([]byte, []int) {
	return file_mount_proto_rawDescGZIP(), []int{7}
}

func (x *PrepareHotRestartResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PrepareHotRestartResponse) GetStatus() *HotRestartStatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

type CancelHotRestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelHotRestartRequest) Reset() {
	*x = CancelHotRestartRequest{}
	mi := &file_mount_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelHotRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelHotRestartRequest) ProtoMessage() {}

func (x *CancelHotRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mount_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelHotRestartRequest.ProtoReflect.Descriptor instead.
func (*CancelHotRestartRequest) Descriptor() ([]byte, []int) {
	return file_mount_proto_rawDescGZIP(), []int{8}
}

type CancelHotRestartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelHotRestartResponse) Reset() {
	*x = CancelHotRestartResponse{}
	mi := &file_mount_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelHotRestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelHotRestartResponse) ProtoMessage() {}

func (x *CancelHotRestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mount_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelHotRestartResponse.ProtoReflect.Descriptor instead.
func (*CancelHotRestartResponse) Descriptor() ([]byte, []int) {
	return file_mount_proto_rawDescGZIP(), []int{9}
}

var File_mount_proto protoreflect.FileDescriptor

const file_mount_proto_rawDesc = "" +
	"\n" +
	"\vmount.proto\x12\fmessaging_pb\"C\n" +
	"\x10ConfigureRequest\x12/\n" +
	"\x13collection_capacity\x18\x01 \x01(\x03R\x12collectionCapacity\"\x13\n" +
	"\x11ConfigureResponse\"\x1f\n" +
	"\x1dRefreshVolumeLocationsRequest\" \n" +
	"\x1eRefreshVolumeLocationsResponse\"\x19\n" +
	"\x17HotRestartStatusRequest\"\x80\x02\n" +
	"\x18HotRestartStatusResponse\x12*\n" +
	"\x11open_file_handles\x18\x01 \x01(\x04R\x0fopenFileHandles\x124\n" +
	"\x16open_directory_handles\x18\x02 \x01(\x04R\x14openDirectoryHandles\x122\n" +
	"\x15pending_async_flushes\x18\x03 \x01(\x04R\x13pendingAsyncFlushes\x12\x1c\n" +
	"\tquiescent\x18\x04 \x01(\bR\tquiescent\x120\n" +
	"\x14blocking_new_handles\x18\x05 \x01(\bR\x12blockingNewHandles\"\x1a\n" +
	"\x18PrepareHotRestartRequest\"w\n" +
	"\x19PrepareHotRestartResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12>\n" +
	"\x06status\x18\x02 \x01(\v2&.messaging_pb.HotRestartStatusResponseR\x06status\"\x19\n" +
	"\x17CancelHotRestartRequest\"\x1a\n" +
	"\x18CancelHotRestartResponse2\x87\x04\n" +
	"\fSeaweedMount\x12N\n" +
	"\tConfigure\x12\x1e.messaging_pb.ConfigureRequest\x1a\x1f.messaging_pb.ConfigureResponse\"\x00\x12u\n" +
	"\x16RefreshVolumeLocations\x12+.messaging_pb.RefreshVolumeLocationsRequest\x1a,.messaging_pb.RefreshVolumeLocationsResponse\"\x00\x12c\n" +
	"\x10HotRestartStatus\x12%.messaging_pb.HotRestartStatusRequest\x1a&.messaging_pb.HotRestartStatusResponse\"\x00\x12f\n" +
	"\x11PrepareHotRestart\x12&.messaging_pb.PrepareHotRestartRequest\x1a'.messaging_pb.PrepareHotRestartResponse\"\x00\x12c\n" +
	"\x10CancelHotRestart\x12%.messaging_pb.CancelHotRestartRequest\x1a&.messaging_pb.CancelHotRestartResponse\"\x00BO\n" +
	"\x10seaweedfs.clientB\n" +
	"MountProtoZ/github.com/seaweedfs/seaweedfs/weed/pb/mount_pbb\x06proto3"

var (
	file_mount_proto_rawDescOnce sync.Once
	file_mount_proto_rawDescData []byte
)

func file_mount_proto_rawDescGZIP() []byte {
	file_mount_proto_rawDescOnce.Do(func() {
		file_mount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mount_proto_rawDesc), len(file_mount_proto_rawDesc)))
	})
	return file_mount_proto_rawDescData
}

var file_mount_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mount_proto_goTypes = []any{
	(*ConfigureRequest)(nil),               // 0: messaging_pb.ConfigureRequest
	(*ConfigureResponse)(nil),              // 1: messaging_pb.ConfigureResponse
	(*RefreshVolumeLocationsRequest)(nil),  // 2: messaging_pb.RefreshVolumeLocationsRequest
	(*RefreshVolumeLocationsResponse)(nil), // 3: messaging_pb.RefreshVolumeLocationsResponse
	(*HotRestartStatusRequest)(nil),        // 4: messaging_pb.HotRestartStatusRequest
	(*HotRestartStatusResponse)(nil),       // 5: messaging_pb.HotRestartStatusResponse
	(*PrepareHotRestartRequest)(nil),       // 6: messaging_pb.PrepareHotRestartRequest
	(*PrepareHotRestartResponse)(nil),      // 7: messaging_pb.PrepareHotRestartResponse
	(*CancelHotRestartRequest)(nil),        // 8: messaging_pb.CancelHotRestartRequest
	(*CancelHotRestartResponse)(nil),       // 9: messaging_pb.CancelHotRestartResponse
}
var file_mount_proto_depIdxs = []int32{
	5, // 0: messaging_pb.PrepareHotRestartResponse.status:type_name -> messaging_pb.HotRestartStatusResponse
	0, // 1: messaging_pb.SeaweedMount.Configure:input_type -> messaging_pb.ConfigureRequest
	2, // 2: messaging_pb.SeaweedMount.RefreshVolumeLocations:input_type -> messaging_pb.RefreshVolumeLocationsRequest
	4, // 3: messaging_pb.SeaweedMount.HotRestartStatus:input_type -> messaging_pb.HotRestartStatusRequest
	6, // 4: messaging_pb.SeaweedMount.PrepareHotRestart:input_type -> messaging_pb.PrepareHotRestartRequest
	8, // 5: messaging_pb.SeaweedMount.CancelHotRestart:input_type -> messaging_pb.CancelHotRestartRequest
	1, // 6: messaging_pb.SeaweedMount.Configure:output_type -> messaging_pb.ConfigureResponse
	3, // 7: messaging_pb.SeaweedMount.RefreshVolumeLocations:output_type -> messaging_pb.RefreshVolumeLocationsResponse
	5, // 8: messaging_pb.SeaweedMount.HotRestartStatus:output_type -> messaging_pb.HotRestartStatusResponse
	7, // 9: messaging_pb.SeaweedMount.PrepareHotRestart:output_type -> messaging_pb.PrepareHotRestartResponse
	9, // 10: messaging_pb.SeaweedMount.CancelHotRestart:output_type -> messaging_pb.CancelHotRestartResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mount_proto_init() }
func file_mount_proto_init() {
	if File_mount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mount_proto_rawDesc), len(file_mount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mount_proto_goTypes,
		DependencyIndexes: file_mount_proto_depIdxs,
		MessageInfos:      file_mount_proto_msgTypes,
	}.Build()
	File_mount_proto = out.File
	file_mount_proto_goTypes = nil
	file_mount_proto_depIdxs = nil
}
